### PR TITLE
JetPack customisation for paid post content

### LINKED ISSUE #1144: JetPack plugin allows access to Paid Content
### Issue 1: Free Access to Paid Content in App
**Steps to Reproduce**
1. Ensure that the WordPress site has JetPack installed
2. Download the WordPress iOS app
3. Add the site to your "followed sites" (Reader > Followed Sites > Manage)
4. From the screen above, click the site and select a paid article

**Observed Result**
The article content is displayed in full for free.

**Desired Result**
Paid content should not be displayed for free. 
A few implementation options include: 
- Display paywall as shown in other places (from step 4 above, click the icon in the top right corner of the app & Open in Safari; here it is displayed correctly)
- Display only the teaser content
- Do not allow the article to appear in the app

### Issue 2: Free Access to Paid Content via Email
**Steps to Reproduce**
1. In the WordPress app, navigate to Me > Notification Settings > select the site you are using for testing
2. Enable "Email me new posts"
3. Create a new, paid post

**Observed Result**
You receive an email displaying the full content for free.

**Desired Result**
Paid articles should not be emailed.

### Technical Notes
It appears that the following hooks can be used to disable the features above.
- https://developer.jetpack.com/hooks/publicize_should_publicize_published_post/
- https://developer.jetpack.com/hooks/jetpack_sync_prevent_sending_post_data/
- https://developer.jetpack.com/hooks/jetpack_is_post_mailable/

### PR DESCRIPTION
**Pull request by thrijith**
Fixes #1144

### CODE REVIEW

File: laterpay/application/Controller/Frontend/Post.php [hunk 1]
```diff
@@ -758,4 +766,44 @@ public function ajax_load_files( LaterPay_Core_Event $event ) {
...
+     *
+     * @wp-hook jetpack_sync_prevent_sending_post_data
+     * @param LaterPay_Core_Event $event
+     *
+     * @return void
+     */
+    public function jetpack_post_publicize( LaterPay_Core_Event $event ) {
+        list( $bool, $post ) = $event->get_arguments() + array( '', '' );
+
+        $is_supported_type = ( in_array( get_post_type( $post->ID ), (array) get_option( 'laterpay_enabled_post_types' ), true ) );
```
Comment (PatelUtkarsh) [inline laterpay/application/Controller/Frontend/Post.php]: Should expand this into variables? Readability concern and possible of empty array on `(array) get_option( 'laterpay_enabled_post_types' )`. @thrijith 

If possible move checking of purchasable content into a separate function.

Comment (PatelUtkarsh) [reply laterpay/application/Controller/Frontend/Post.php]: Or we can add more checks inside `LaterPay_Helper_Pricing::is_purchasable` itself but need to check other refs.
