### PR TITLE
Fix issue with purchase verification.

### LINKED ISSUE #1036: Purchase verification failure when buying via Shortcode or when the Permalink structure is plain
Scenario: The permalink structure is set as `Plain`

And user buys content even after a successful purchase user is redirected to the content page with paywall still showing. 

The same issue happens with Shortcode purchase too.

### PR DESCRIPTION
**Pull request by thrijith**
Fix issue with purchase verification on `Plain` permalink strucure.
Fix issue with shortcode purchase.

Fixes #1036

### CODE REVIEW

File: laterpay/application/Helper/Post.php [hunk 1]
```diff
@@ -196,13 +196,37 @@ public static function get_laterpay_purchase_link( $post_id, $current_post_id =
...
+        // if params exists in uri.
         if ( ! empty( $parsed_link[1] ) ) {
-            $back_url .= '&' . $parsed_link[1];
+
+            // If parsed link has extra params process them accordingly.
+            parse_str( $parsed_link[1], $extra_params );
+
+            // Get query args in the already built url.
+            $parsed_url = wp_parse_url( $back_url );
+            parse_str( $parsed_url['query'], $parsed_url_params );
```
Comment (PatelUtkarsh) [inline laterpay/application/Helper/Post.php]: Check if `$parsed_url['query']` exists?

File: laterpay/application/Helper/TimePass.php [hunk 2]
```diff
@@ -466,11 +469,32 @@ public static function get_laterpay_purchase_link( $time_pass_id, $data = null,
...
+                    unset( $value );
+
+                    // Don't add array / existing params to url building array.
+                    if ( is_array( $extra_params[$key] ) || isset( $url_params[$key] ) || isset( $parsed_url_params[$key] ) ) {
+                        unset( $extra_params[$key] );
+                    }
+                }
+
+                // Build back URL according to new params.
+                $back_url = add_query_arg( $extra_params, $back_url );
```
Comment (PatelUtkarsh) [inline laterpay/application/Helper/TimePass.php]: This seems duplicate code from above, can we move it to a function if possible?

File: laterpay/application/Module/Purchase.php [hunk 3]
```diff
@@ -538,8 +538,26 @@ public function buy_post() {
...
             $redirect_url = get_permalink( $request->get_param( 'post_id' ) );
 
+            // Redirect back to Shortcode page if it was a Shortcode purchase.
+            if ( ! empty( $params['parent_pid'] ) ) {
+                $redirect_url = get_permalink( $request->get_param( 'parent_pid' ) );
+                unset( $params['parent_pid'], $params['action'], $params['attachment_id'] );
+            }
+
+            // If permalink contains query string then build back url accordingly.
+            if ( strpos( $redirect_url, '?' ) ) {
```
Comment (PatelUtkarsh) [inline laterpay/application/Module/Purchase.php]: Can use parse_url? http://php.net/manual/en/function.parse-url.php
